# This map defines the Consul KV resources that are consumed by consul_kv.tf
# Generated by scripts/generate-vars.sh. 
# Copy to /terraform/services/consul_kv.auto.tfvars

consul_kv = {

  coredns = {
    filenames = [
      "corefile.tftpl",
      "zonefile.tftpl",
    ]
  }

  loki = {
    filenames = ["loki.yaml"]
  }

  mqtt = {
    filenames = ["mosquitto.conf"]
  }

  prometheus = {
    filenames = ["prometheus.yaml"]
  }

  traefik = {
    filenames = [
      "dynamic.yaml",
      "traefik.yaml",
    ]
  }

  vector = {
    filenames = ["vector.yaml"]
  }

}
