# This map defines the Consul KV resources that are consumed by consul_kv.tf
# Generated by scripts/generate-tfvars.sh

consul_kv = {

  coredns = {
    filenames = [
      "corefile.tftpl",
      "zonefile.tftpl",
    ]
  }

  hass = {
    filenames = [
      "automations.yaml",
      "binary_sensors.yaml",
      "configuration.yaml",
      "covers.yaml",
      "customize.yaml",
      "device_tracker.yaml",
      "fans.yaml",
      "ip_bans.yaml",
      "lights.yaml",
      "media_players.yaml",
      "scripts.yaml",
      "switches.yaml",
      "trusted_proxies.yaml",
    ]
  }

  loki = {
    filenames = ["loki.yaml"]
  }

  mqtt = {
    filenames = ["mosquitto.conf"]
  }

  prometheus = {
    filenames = ["prometheus.yaml"]
  }

  traefik = {
    filenames = [
      "dynamic.yaml",
      "traefik.yaml",
    ]
  }

  vector = {
    filenames = ["vector.yaml"]
  }

}
