# This map defines the Nomad jobs map that is consumed by nomad_jobs.tf
# Each job in the map can contain its own template vars e.g. coredns = {version="1.11.1"}
# Generated by scripts/generate-vars.sh — copy to /terraform/services/nomad_jobs.auto.tfvars,
# fill in values and move jobs to the correct tier

nomad_jobs = {
  primary = {
    jobs = {
      auth = { version = "latest" }
      cannery = { version = "latest" }
      cloudflared = {}
      code-server = { version = "latest" }
      coredns = { version = "latest" }
      cyberchef = { version = "latest" }
      deluge = { version = "latest" }
      docker-cleanup = {}
      drawio = { version = "latest" }
      emulatorjs = { version = "latest" }
      flaresolverr = { version = "latest" }
      gitea = { version = "latest" }
      grafana = { version = "latest" }
      home-assistant = {}
      influxdb = { version = "latest" }
      jellyfin = { version = "latest" }
      journalctl-cleanup = {}
      keepalived = {}
      loki = { version = "latest" }
      matter = { version = "latest" }
      mongodb8 = { version = "latest" }
      mosquitto = { version = "latest" }
      motioneye = { version = "latest" }
      n8n = { version = "latest" }
      nginx = { version = "latest" }
      nomad-cleanup = {}
      ollama = { version = "latest" }
      pgweb = { version = "latest" }
      plex = { version = "latest" }
      postgres = { version = "latest" }
      privatebin = { version = "latest" }
      prometheus = { version = "latest" }
      prowlarr = { version = "latest" }
      radarr = { version = "latest" }
      sabnzbd = { version = "latest" }
      samba = {}
      sonarr = { version = "latest" }
      storage-controller = { version = "latest" }
      storage-node = { version = "latest" }
      traefik = { version = "latest" }
      transmission = { version = "latest" }
      unifi = { version = "latest" }
      vaultwarden = { version = "latest" }
      vector = { version = "latest" }
      wikijs = { version = "latest" }
    }
  }

  secondary = {
    jobs = {
      # Move jobs here that depend on primary services
    }
  }

  tertiary = {
    jobs = {
      # Move jobs here that depend on secondary services
    }
  }
}
