# This map defines the Nomad jobs map that is consumed by nomad_jobs.tf
# Each job in the map can contain its own template vars e.g. coredns = {version="1.11.1"}
# Generated by scripts/generate-tfvars.sh — fill in values and move jobs to the correct tier

nomad_jobs = {
  primary = {
    jobs = {
      auth = { version = "latest" }
      cannery = {}
      cloudflared = {}
      coredns = { version = "latest" }
      data-node = {}
      docker-cleanup = {}
      docker-registry = {}
      drawio = { version = "latest" }
      emulatorjs = { version = "latest" }
      flaresolverr = { version = "latest" }
      grafana = { version = "latest" }
      graylog = {}
      home-assistant = {}
      influxdb = { version = "latest" }
      jellyfin = { version = "latest" }
      journalctl-cleanup = {}
      keepalived = {}
      loki = { version = "latest" }
      matter = { version = "latest" }
      mongodb6 = {}
      mongodb7 = {}
      mongodb8 = { version = "latest" }
      mosquitto = { version = "latest" }
      motioneye = { version = "latest" }
      n8n = { version = "latest" }
      nginx = { version = "latest" }
      nomad-cleanup = {}
      ollama = { version = "latest" }
      pgweb = { version = "latest" }
      plex = { version = "latest" }
      postgres = { version = "latest" }
      prometheus = { version = "latest" }
      prowlarr = { version = "latest" }
      radarr = { version = "latest" }
      sabnzbd = { version = "latest" }
      samba = {}
      sonarr = { version = "latest" }
      storage-controller = {}
      storage-node = {}
      traefik = { version = "latest" }
      transmission = { version = "latest" }
      unifi = { version = "latest" }
      vaultwarden = { version = "latest" }
      vector = { version = "latest" }
      wikijs = { version = "latest" }
    }
  }

  secondary = {
    jobs = {
      # Move jobs here that depend on primary services
    }
  }

  tertiary = {
    jobs = {
      # Move jobs here that depend on secondary services
    }
  }
}
