# This map defines the Nomad Variables that are consumed by nomad_vars.tf
# Generated by scripts/generate-vars.sh
# Copy to /terraform/services/nomad_vars.auto.tfvars and populate with real data

nomad_vars = {
  auth = {
    vars = {
      EXAMPLE_KEY = "CHANGEME"
    }
  }

  cannery = {
    vars = {
      EXAMPLE_KEY = "CHANGEME"
    }
  }

  cloudflared = {
    vars = {
      EXAMPLE_KEY = "CHANGEME"
    }
  }

  grafana = {
    vars = {
      EXAMPLE_KEY = "CHANGEME"
    }
  }

  influxdb = {
    vars = {
      EXAMPLE_KEY = "CHANGEME"
    }
  }

  mongo = {
    vars = {
      EXAMPLE_KEY = "CHANGEME"
    }
  }

  mqtt = {
    vars = {
      EXAMPLE_KEY = "CHANGEME"
    }
  }

  postgres = {
    vars = {
      EXAMPLE_KEY = "CHANGEME"
    }
  }

  samba = {
    vars = {
      EXAMPLE_KEY = "CHANGEME"
    }
  }

  unifi = {
    vars = {
      EXAMPLE_KEY = "CHANGEME"
    }
  }

}
