# This map contains vars that are used in config definitions and template variables
# Generated by scripts/generate-vars.sh
# Copy to /terraform/services/services.auto.tfvars and populate with real data


env = {
  nomad_addr        = "http://192.168.X.X:4646"     # REQUIRED: used in provider.tf
  consul_addr       = "http://192.168.X.X:8500"     # REQUIRED: used in provider.tf
  secret_id         = "CHANGEME"                    # REQUIRED: used in providers.tf 
  host_storage_path = "/mnt"                        # REQUIRED: used in nomad_volumes.tf
  storage_type      = "host"                        # REQUIRED: used in nomad_volumes.tf
  domain            = "example.com"                 # used in nomad jobs, consul templates 
  lab_name          = "terralab"                    # used in nomad jobs
  consul_domain     = "service.consul"              # used in nomad jobs
  datacenter        = "dc1"                         # used in nomad jobs 
  region            = "global"                      # used in nomad jobs
  cidr              = "192.168.X.0/24"              # used in nomad jobs 
  virtual_ip        = "192.168.X.X"                 # used in nomad jobs  
  dns               = "192.168.X.X"                 # used in nomad jobs
  uid               = 1000                          # used in nomad jobs 
  gid               = 1000                          # used in nomad jobs 
  timezone          = "America/Region"              # used in nomad jobs 
  pfsense_addr      = "https://192.168.x.x:8443"    # used in nomad jobs 
  pve_addr          = "http://192.168.x.x:8006"     # used in nomad jobs 
  pve_backup_addr   = "http://192.168.x.x:8007"     # used in nomad jobs 
}
