# This map defines volumes that are consumed by nomad_volumes.tf
# Generated by scripts/generate-vars.sh. 
# Copy to /terraform/services/volumes.auto.tfvars
# Restrict a volume by addingthe hosts property 
# e.g. arcade = {hosts = [ "worker02" ]}


volumes = {

  arcade = {
    volume_id   = "arcade"
    external_id = "arcade"
    access_mode = "single-node-writer"
  }

  arcade-config = {
    volume_id   = "arcade-config"
    external_id = "arcade-config"
    access_mode = "single-node-writer"
  }

  certs = {
    volume_id   = "certs"
    external_id = "certs"
    access_mode = "single-node-writer"
  }

  code-server = {
    volume_id   = "code-server"
    external_id = "code-server"
    access_mode = "single-node-writer"
  }

  deluge = {
    volume_id   = "deluge"
    external_id = "deluge"
    access_mode = "single-node-writer"
  }

  docker_registry = {
    volume_id   = "docker_registry"
    external_id = "docker_registry"
    access_mode = "single-node-writer"
  }

  downloads = {
    volume_id   = "downloads"
    external_id = "downloads"
    access_mode = "single-node-writer"
  }

  flaresolverr = {
    volume_id   = "flaresolverr"
    external_id = "flaresolverr"
    access_mode = "single-node-writer"
  }

  gitea = {
    volume_id   = "gitea"
    external_id = "gitea"
    access_mode = "single-node-writer"
  }

  grafana = {
    volume_id   = "grafana"
    external_id = "grafana"
    access_mode = "single-node-writer"
  }

  hass = {
    volume_id   = "hass"
    external_id = "hass"
    access_mode = "single-node-writer"
  }

  influxdb = {
    volume_id   = "influxdb"
    external_id = "influxdb"
    access_mode = "single-node-writer"
  }

  influxdb-config = {
    volume_id   = "influxdb-config"
    external_id = "influxdb-config"
    access_mode = "single-node-writer"
  }

  jellyfin = {
    volume_id   = "jellyfin"
    external_id = "jellyfin"
    access_mode = "single-node-writer"
  }

  loki = {
    volume_id   = "loki"
    external_id = "loki"
    access_mode = "single-node-writer"
  }

  matter = {
    volume_id   = "matter"
    external_id = "matter"
    access_mode = "single-node-writer"
  }

  media = {
    volume_id   = "media"
    external_id = "media"
    access_mode = "single-node-writer"
  }

  mongo = {
    volume_id   = "mongo"
    external_id = "mongo"
    access_mode = "single-node-writer"
  }

  mosquitto = {
    volume_id   = "mosquitto"
    external_id = "mosquitto"
    access_mode = "single-node-writer"
  }

  mosquitto-data = {
    volume_id   = "mosquitto-data"
    external_id = "mosquitto-data"
    access_mode = "single-node-writer"
  }

  mosquitto-log = {
    volume_id   = "mosquitto-log"
    external_id = "mosquitto-log"
    access_mode = "single-node-writer"
  }

  motioneye-etc = {
    volume_id   = "motioneye-etc"
    external_id = "motioneye-etc"
    access_mode = "single-node-writer"
  }

  motioneye-shared = {
    volume_id   = "motioneye-shared"
    external_id = "motioneye-shared"
    access_mode = "single-node-writer"
  }

  n8n = {
    volume_id   = "n8n"
    external_id = "n8n"
    access_mode = "single-node-writer"
  }

  ollama = {
    volume_id   = "ollama"
    external_id = "ollama"
    access_mode = "single-node-writer"
  }

  open-webui = {
    volume_id   = "open-webui"
    external_id = "open-webui"
    access_mode = "single-node-writer"
  }

  plex = {
    volume_id   = "plex"
    external_id = "plex"
    access_mode = "single-node-writer"
  }

  postgres = {
    volume_id   = "postgres"
    external_id = "postgres"
    access_mode = "single-node-writer"
  }

  privatebin = {
    volume_id   = "privatebin"
    external_id = "privatebin"
    access_mode = "single-node-writer"
  }

  projects = {
    volume_id   = "projects"
    external_id = "projects"
    access_mode = "single-node-writer"
  }

  prowlarr = {
    volume_id   = "prowlarr"
    external_id = "prowlarr"
    access_mode = "single-node-writer"
  }

  radarr = {
    volume_id   = "radarr"
    external_id = "radarr"
    access_mode = "single-node-writer"
  }

  sabnzbd = {
    volume_id   = "sabnzbd"
    external_id = "sabnzbd"
    access_mode = "single-node-writer"
  }

  sonarr = {
    volume_id   = "sonarr"
    external_id = "sonarr"
    access_mode = "single-node-writer"
  }

  traefik-logs = {
    volume_id   = "traefik-logs"
    external_id = "traefik-logs"
    access_mode = "single-node-writer"
  }

  transmission = {
    volume_id   = "transmission"
    external_id = "transmission"
    access_mode = "single-node-writer"
  }

  unifi = {
    volume_id   = "unifi"
    external_id = "unifi"
    access_mode = "single-node-writer"
  }

  vaultwarden = {
    volume_id   = "vaultwarden"
    external_id = "vaultwarden"
    access_mode = "single-node-writer"
  }

  wikijs = {
    volume_id   = "wikijs"
    external_id = "wikijs"
    access_mode = "single-node-writer"
  }

}
