job "loki" {
  datacenters = ["dc1"]
  type        = "service"

  group "loki" {
    # Ensure you have a host volume named "loki_data" in your client config!

    network {
      port "http" { static = 3100 }
    }

    volume "loki" {
      type            = "${storage_mode}"
      source          = "loki"
      attachment_mode = "file-system"
      access_mode     = "single-node-writer"
    }

    service {
      name = "loki"
      port = "http"
    }

    task "loki" {
      driver = "docker"


      config {
        image = "grafana/loki:latest"
        ports = ["http"]
        # Point Loki to the config file generated by the template below
        args = ["-config.file=/local/loki-config.yaml"]
      }

      volume_mount {
        volume      = "loki"
        destination = "/loki"
      }

      template {
        destination = "local/loki-config.yaml"
        data = <<EOH
auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

# This section keeps your Proxmox host from filling up!
limits_config:
  retention_period: 168h # Delete logs after 7 days
EOH
      }
    }
  }
}