#!/usr/bin/env bash
#
# generate-vars.sh - Generate skeleton .auto.tfvars templates from the project
#
# Scans nomad job files, consul_kv directories, to produce template 
# tfvars|pkrvars in the tfvars|pkrvars subdirectories with placeholder values.
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SERVICES_DIR="$ROOT/terraform/services"
CLUSTER_DIR="$ROOT/terraform/cluster"
PACKER_DIR="$ROOT/packer"
JOBS_DIR="$SERVICES_DIR/nomad_jobs"
CONSUL_KV_DIR="$SERVICES_DIR/consul_kv"
NOMAD_VARS_DIR="$SERVICES_DIR/nomad_vars"

# Output directories
SERVICES_TFVARS="$SERVICES_DIR/tfvars"
CLUSTER_TFVARS="$CLUSTER_DIR/tfvars"
PACKER_PKRVARS="$PACKER_DIR/pkrvars"

mkdir -p "$SERVICES_TFVARS" "$CLUSTER_TFVARS" "$PACKER_PKRVARS"

# ─── Helper ──────────────────────────────────────────────────────────────────

log() { echo "  → $1"; }

# ─── 1. Generate nomad_jobs.auto.tfvars ──────────────────────────────────────

generate_nomad_jobs() {
  local out="$SERVICES_TFVARS/nomad_jobs.auto.tfvars.template"
  log "Scanning $JOBS_DIR for job definitions..."

  # Collect all job filenames (without extension)
  local jobs=()
  for f in "$JOBS_DIR"/*.hcl; do
    jobs+=("$(basename "$f" .hcl)")
  done

  cat > "$out" <<'HEADER'
# This map defines the Nomad jobs map that is consumed by nomad_jobs.tf
# Each job in the map can contain its own template vars e.g. coredns = {version="1.11.1"}
# Generated by scripts/generate-vars.sh — copy to /terraform/services/nomad_jobs.auto.tfvars,
# fill in values and move jobs to the correct tier

nomad_jobs = {
  primary = {
    jobs = {
HEADER

  for job in "${jobs[@]}"; do
    local file="$JOBS_DIR/${job}.hcl"
    # Check if the job uses ${version} as a template variable
    if grep -qP '(?<!\$)\$\{version\}' "$file" 2>/dev/null; then
      printf '      %s = { version = "latest" }\n' "$job" >> "$out"
    else
      printf '      %s = {}\n' "$job" >> "$out"
    fi
  done

  cat >> "$out" <<'FOOTER'
    }
  }

  secondary = {
    jobs = {
      # Move jobs here that depend on primary services
    }
  }

  tertiary = {
    jobs = {
      # Move jobs here that depend on secondary services
    }
  }
}
FOOTER

  log "Wrote $out ($(echo "${jobs[@]}" | wc -w) jobs found)"
}

# ─── 2. Generate volumes.auto.tfvars ────────────────────────────────────────

generate_volumes() {
  local out="$SERVICES_TFVARS/volumes.auto.tfvars.template"
  log "Scanning $JOBS_DIR for volume declarations..."

  # Extract unique volume names from all job files
  local volumes
  volumes=$(grep -hPo 'volume\s+"[^"]+"' "$JOBS_DIR"/*.hcl \
    | grep -oP '"[^"]+"' \
    | tr -d '"' \
    | sort -u)

  cat > "$out" <<'HEADER'
# This map defines volumes that are consumed by nomad_volumes.tf
# Generated by scripts/generate-vars.sh. 
# Copy to /terraform/services/volumes.auto.tfvars


volumes = {
HEADER

  local count=0
  for vol in $volumes; do
    count=$((count + 1))
    cat >> "$out" <<EOF

  ${vol} = {
    volume_id   = "${vol}"
    external_id = "${vol}"
    access_mode = "single-node-writer"
  }
EOF
  done

  printf '\n}\n' >> "$out"
  log "Wrote $out ($count volumes found)"
}

# ─── 3. Generate services.auto.tfvars ─────────────────────────────────────────────

generate_env() {
  local out="$SERVICES_TFVARS/services.auto.tfvars.template"
  log "Scanning templates and terraform files for variables..."

  # 1. Extract ${var} from template files (skip Nomad runtime $${} vars)
  local template_vars
  template_vars=$(grep -rhoP '(?<!\$)\$\{\K\w+(?=\})' \
    "$JOBS_DIR"/*.hcl \
    "$CONSUL_KV_DIR"/*/* \
    "$NOMAD_VARS_DIR"/*.tftpl 2>/dev/null \
    | sort -u)

  # 2. Extract var.env.xxx and local.vars.xxx from .tf files
  local tf_vars
  tf_vars=$(grep -rhoP '(?:var\.env|local\.vars)\.\K\w+' \
    "$SERVICES_DIR"/*.tf 2>/dev/null \
    | sort -u)

  # 3. Combine, deduplicate, and exclude job-specific vars (version is per-job)
  local all_vars
  all_vars=$(printf '%s\n' $template_vars $tf_vars | grep -v '^version$' | sort -u)

  # 4. Find longest variable name for alignment
  local max_len=0
  for var in $all_vars; do
    (( ${#var} > max_len )) && max_len=${#var}
  done

  # 5. Write env map
  cat > "$out" <<'HEADER'
# env map - template variables used across nomad jobs, consul kv, and nomad vars
# Generated by scripts/generate-vars.sh
# Copy to /terraform/services/services.auto.tfvars and populate with real data

env = {
HEADER

  for var in $all_vars; do
    printf '  %-*s = "CHANGEME"\n' "$max_len" "$var" >> "$out"
  done

  echo "}" >> "$out"
  log "Wrote $out ($(echo $all_vars | wc -w) variables found)"
}

# ─── 4. Generate cluster.auto.tfvars ────────────────────────────────────────

generate_cluster() {
  local out="$CLUSTER_TFVARS/cluster.auto.tfvars.template"
  log "Generating cluster variable template..."

  cat > "$out" <<'EOF'
env = {
  datacenter      = "dc1"
  region          = "global"  
  cidr            = "192.168.X.0/24"
  ciuser          = "CHANGEME"
  cipassword      = "CHANGEME"
  sshkeys         = "ssh-rsa AAAA... user@host"
  domain          = "example.com"
  dns             = "192.168.X.X"
  pve_nodes       = ["pve01", "pve02", "pve03"]

  provider = {
    url      = "https://192.168.X.X:8006"
    user     = "root@pam"
    password = "CHANGEME"
  }

  worker = {

    clone     = "worker-tpl"
    clone_id  = 9002
    disk_size = 30
    cores     = 12
    memory    = 65536
    offset    = 81
    count     = 3
  }

  manager = {
    clone     = "manager-tpl"
    clone_id  = 9001
    disk_size = 8
    cores     = 4
    memory    = 8192
    offset    = 71
    count     = 3
  }

  vm = {
    storage             = "rbd"
    cloud_init_storage  = "cephfs"
    full_clone          = true
    cpu_type            = "host"
    agent_enabled       = true
    bridge              = "vmbr2"
    network_model       = "virtio"
    disk_interface      = "scsi0"
    disk_iothread       = true
    disk_discard        = "on"
    disk_ssd            = true
    cloudinit_interface = "ide0"
    vlan_id             = ""
  }
}
EOF

  log "Wrote $out"
}

generate_packer() {
  local out="$PACKER_PKRVARS/packer.pkrvars.template"
  log "Generating packer variable template..."

  cat > "$out" <<'EOF'
# This map contains vars that are used in packer templates
# Generated by scripts/generate-vars.sh
# Copy to /packer/packer.pkrvars and populate with real data

env = {
  proxmox_url="http://192.168.x.x:8006/api2/json"
  proxmox_user="user"
  proxmox_password="password"
  proxmox_node="node"
  ssh_username="user"
  ssh_password="password"

  os              = "os"
  cpu_type        = "cpu"
  sockets         = 1
  cores           = 2
  memory          = 2048
  machine         = "pc"
  scsi_controller = "virtio-scsi-single"
  qemu_agent      = true
  
  cloud_init              = true
  cloud_init_storage_pool = "cloud_init_storage"

  vga = {
    type = "std"
  }

  network_adapters = {
    model    = "virtio"    
    bridge   = "vmbr2"
  }

  disks = {
    disk_size    = "6G"
    storage_pool = "storage_pool"
    type         = "scsi"
  }

  boot = {
    type     = "scsi"
    iso      = "local:iso/debian-13.3.0-amd64-netinst.iso"
    unmount  = true
  }

}
EOF

  log "Wrote $out"
}

# ─── Main ────────────────────────────────────────────────────────────────────

echo "Generating tfvars templates from project..."
echo ""

generate_nomad_jobs
generate_volumes
generate_env
generate_cluster
generate_packer

echo ""
echo "Done. Templates written to:"
echo "  $SERVICES_TFVARS/"
echo "  $CLUSTER_TFVARS/"
echo "  $PACKER_PKRVARS/"
echo ""
echo "Review the generated files, fill in placeholder values, then copy"
echo "them to their parent directories as .auto.tfvars files."
