#!/usr/bin/env bash
#
# generate-tfvars.sh - Generate skeleton .auto.tfvars templates from the project
#
# Scans nomad job files, consul_kv directories, and variables.tf to produce
# template tfvars in the tfvars/ subdirectories with placeholder values.
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SERVICES_DIR="$ROOT/terraform/services"
CLUSTER_DIR="$ROOT/terraform/cluster"
JOBS_DIR="$SERVICES_DIR/nomad_jobs"
CONSUL_KV_DIR="$SERVICES_DIR/consul_kv"

# Output directories
SERVICES_TFVARS="$SERVICES_DIR/tfvars"
CLUSTER_TFVARS="$CLUSTER_DIR/tfvars"

mkdir -p "$SERVICES_TFVARS" "$CLUSTER_TFVARS"

# ─── Helper ──────────────────────────────────────────────────────────────────

log() { echo "  → $1"; }

# ─── 1. Generate nomad_jobs.auto.tfvars ──────────────────────────────────────

generate_nomad_jobs() {
  local out="$SERVICES_TFVARS/var.nomad_jobs.auto.tfvars"
  log "Scanning $JOBS_DIR for job definitions..."

  # Collect all job filenames (without extension)
  local jobs=()
  for f in "$JOBS_DIR"/*.hcl; do
    jobs+=("$(basename "$f" .hcl)")
  done

  cat > "$out" <<'HEADER'
# This map defines the Nomad jobs map that is consumed by nomad_jobs.tf
# Each job in the map can contain its own template vars e.g. coredns = {version="1.11.1"}
# Generated by scripts/generate-tfvars.sh — fill in values and move jobs to the correct tier

nomad_jobs = {
  primary = {
    jobs = {
HEADER

  for job in "${jobs[@]}"; do
    local file="$JOBS_DIR/${job}.hcl"
    # Check if the job uses ${version} as a template variable
    if grep -qP '(?<!\$)\$\{version\}' "$file" 2>/dev/null; then
      printf '      %s = { version = "latest" }\n' "$job" >> "$out"
    else
      printf '      %s = {}\n' "$job" >> "$out"
    fi
  done

  cat >> "$out" <<'FOOTER'
    }
  }

  secondary = {
    jobs = {
      # Move jobs here that depend on primary services
    }
  }

  tertiary = {
    jobs = {
      # Move jobs here that depend on secondary services
    }
  }
}
FOOTER

  log "Wrote $out ($(echo "${jobs[@]}" | wc -w) jobs found)"
}

# ─── 2. Generate consul_kv.auto.tfvars ──────────────────────────────────────

generate_consul_kv() {
  local out="$SERVICES_TFVARS/var.consul_kv.auto.tfvars"
  log "Scanning $CONSUL_KV_DIR for configuration templates..."

  cat > "$out" <<'HEADER'
# This map defines the Consul KV resources that are consumed by consul_kv.tf
# Generated by scripts/generate-tfvars.sh

consul_kv = {
HEADER

  local count=0
  for dir in "$CONSUL_KV_DIR"/*/; do
    [[ -d "$dir" ]] || continue
    local service
    service=$(basename "$dir")
    count=$((count + 1))

    # Collect filenames in the directory
    local files=()
    for f in "$dir"*; do
      [[ -f "$f" ]] && files+=("$(basename "$f")")
    done

    printf '\n  %s = {\n' "$service" >> "$out"
    printf '    filenames = [' >> "$out"

    if [[ ${#files[@]} -eq 1 ]]; then
      printf '"%s"' "${files[0]}" >> "$out"
    else
      echo "" >> "$out"
      for f in "${files[@]}"; do
        printf '      "%s",\n' "$f" >> "$out"
      done
      printf '    ' >> "$out"
    fi

    printf ']\n  }\n' >> "$out"
  done

  printf '\n}\n' >> "$out"
  log "Wrote $out ($count services found)"
}

# ─── 3. Generate volumes.auto.tfvars ────────────────────────────────────────

generate_volumes() {
  local out="$SERVICES_TFVARS/var.volumes.auto.tfvars"
  log "Scanning $JOBS_DIR for volume declarations..."

  # Extract unique volume names from all job files
  local volumes
  volumes=$(grep -hPo 'volume\s+"[^"]+"' "$JOBS_DIR"/*.hcl \
    | grep -oP '"[^"]+"' \
    | tr -d '"' \
    | sort -u)

  cat > "$out" <<'HEADER'
# This map defines volumes that are consumed by nomad_volumes.tf
# Generated by scripts/generate-tfvars.sh

volumes = {
HEADER

  local count=0
  for vol in $volumes; do
    count=$((count + 1))
    cat >> "$out" <<EOF

  ${vol} = {
    volume_id   = "${vol}"
    external_id = "${vol}"
    access_mode = "single-node-writer"
  }
EOF
  done

  printf '\n}\n' >> "$out"
  log "Wrote $out ($count volumes found)"
}

# ─── 4. Generate nomad_vars.auto.tfvars ─────────────────────────────────────

generate_nomad_vars() {
  local out="$SERVICES_TFVARS/var.nomad_vars.auto.tfvars"
  log "Scanning $JOBS_DIR for nomadVar references..."

  # Extract unique nomadVar path segments from all job files
  local var_paths
  var_paths=$(grep -hPo 'nomadVar\s+"nomad/jobs/[a-zA-Z0-9_-]+"' "$JOBS_DIR"/*.hcl \
    | grep -oP 'nomad/jobs/\K[a-zA-Z0-9_-]+' \
    | sort -u)

  cat > "$out" <<'HEADER'
# This map defines the Nomad Variables that are consumed by nomad_vars.tf
# Generated by scripts/generate-tfvars.sh — fill in actual secret values

nomad_vars = {
HEADER

  local count=0
  for vp in $var_paths; do
    count=$((count + 1))
    cat >> "$out" <<EOF
  ${vp} = {
    vars = {
      EXAMPLE_KEY = "CHANGEME"
    }
  }

EOF
  done

  printf '}\n' >> "$out"
  log "Wrote $out ($count variable groups found)"
}

# ─── 5. Generate services.auto.tfvars ─────────────────────────────────────────────

generate_env() {
  local out="$SERVICES_TFVARS/var.services.auto.tfvars"
  log "Generating environment variable template..."

  cat > "$out" <<'EOF'
# This map contains vars that are used in config definitions and template variables
# Generated by scripts/generate-tfvars.sh — fill in actual values

env = {
  nomad_addr        = "http://192.168.X.X:4646"     # REQUIRED: used in provider.tf
  consul_addr       = "http://192.168.X.X:8500"     # REQUIRED: used in provider.tf
  secret_id         = "CHANGEME"                    # REQUIRED: used in providers.tf 
  host_storage_path = "/mnt"                        # REQUIRED: used in nomad_volumes.tf
  storage_type      = "host"                        # REQUIRED: used in nomad_volumes.tf
  domain            = "example.com"                 # used in nomad jobs, consul templates 
  lab_name          = "terralab"                    # used in nomad jobs
  consul_domain     = "service.consul"              # used in nomad jobs
  datacenter        = "dc1"                         # used in nomad jobs 
  region            = "global"                      # used in nomad jobs
  cidr              = "192.168.X.0/24"              # used in nomad jobs 
  virtual_ip        = "192.168.X.X"                 # used in nomad jobs  
  dns               = "192.168.X.X"                 # used in nomad jobs
  uid               = 1000                          # used in nomad jobs 
  gid               = 1000                          # used in nomad jobs 
  timezone          = "America/Region"              # used in nomad jobs 
  pfsense_addr      = "https://192.168.x.x:8443"    # used in nomad jobs 
  pve_addr          = "http://192.168.x.x:8006"     # used in nomad jobs 
  pve_backup_addr   = "http://192.168.x.x:8007"     # used in nomad jobs 
}
EOF

  log "Wrote $out"
}

# ─── 6. Generate cluster.auto.tfvars ────────────────────────────────────────

generate_cluster() {
  local out="$CLUSTER_TFVARS/var.cluster.auto.tfvars"
  log "Generating cluster variable template..."

  cat > "$out" <<'EOF'
env = {
  datacenter      = "dc1"
  region          = "global"  
  cidr            = "192.168.X.0/24"
  ciuser          = "CHANGEME"
  cipassword      = "CHANGEME"
  sshkeys         = "ssh-rsa AAAA... user@host"
  domain          = "example.com"
  dns             = "192.168.X.X"
  pve_nodes       = ["pve01", "pve02", "pve03"]

  provider = {
    url      = "https://192.168.X.X:8006"
    user     = "root@pam"
    password = "CHANGEME"
  }

  worker = {

    clone     = "worker-tpl"
    clone_id  = 9002
    disk_size = 30
    cores     = 12
    memory    = 65536
    offset    = 81
    count     = 3
  }

  manager = {
    clone     = "manager-tpl"
    clone_id  = 9001
    disk_size = 8
    cores     = 4
    memory    = 8192
    offset    = 71
    count     = 3
  }

  vm = {
    storage             = "rbd"
    cloud_init_storage  = "cephfs"
    full_clone          = true
    cpu_type            = "host"
    agent_enabled       = true
    bridge              = "vmbr2"
    network_model       = "virtio"
    disk_interface      = "scsi0"
    disk_iothread       = true
    disk_discard        = "on"
    disk_ssd            = true
    cloudinit_interface = "ide0"
    vlan_id             = ""
  }
}
EOF

  log "Wrote $out"
}

# ─── Main ────────────────────────────────────────────────────────────────────

echo "Generating tfvars templates from project..."
echo ""

generate_nomad_jobs
generate_consul_kv
generate_volumes
generate_nomad_vars
generate_env
generate_cluster

echo ""
echo "Done. Templates written to:"
echo "  $SERVICES_TFVARS/"
echo "  $CLUSTER_TFVARS/"
echo ""
echo "Review the generated files, fill in placeholder values, then copy"
echo "them to their parent directories as .auto.tfvars files."
