#!/usr/bin/env bash
#
# generate-vars.sh - Generate skeleton .auto.tfvars templates from the project
#
# Scans nomad_jobs/ directories for job HCL files, consul_kv configs, and
# .nv.yaml vars to produce tfvars|pkrvars templates and per-job volumes.yaml files.
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SERVICES_DIR="$ROOT/terraform/services"
CLUSTER_DIR="$ROOT/terraform/cluster"
PACKER_DIR="$ROOT/packer"
JOBS_DIR="$SERVICES_DIR/nomad_jobs"

# Output directories
SERVICES_TFVARS="$SERVICES_DIR/tfvars"
CLUSTER_TFVARS="$CLUSTER_DIR/tfvars"
PACKER_PKRVARS="$PACKER_DIR/pkrvars"

mkdir -p "$SERVICES_TFVARS" "$CLUSTER_TFVARS" "$PACKER_PKRVARS"

# ─── Helper ──────────────────────────────────────────────────────────────────

log() { echo "  → $1"; }

# ─── 1. Generate nomad_jobs.auto.tfvars ──────────────────────────────────────

generate_nomad_jobs() {
  local out="$SERVICES_TFVARS/nomad_jobs.auto.tfvars.template"
  log "Scanning $JOBS_DIR for job definitions..."

  # Collect job names from top-level directories under nomad_jobs/
  # Each directory is a job; Terraform resolves the HCL as {dir}/{dir}.hcl
  local jobs=()
  for job_dir in "$JOBS_DIR"/*/; do
    [[ -d "$job_dir" ]] && jobs+=("$(basename "$job_dir")")
  done

  cat > "$out" <<'HEADER'
# This map defines the Nomad jobs consumed by nomad_jobs.tf
# Jobs are referenced by directory name under nomad_jobs/ (e.g. "gitea" -> nomad_jobs/gitea/gitea.hcl)
# Generated by scripts/generate-vars.sh — copy to /terraform/services/var.nomad_jobs.auto.tfvars
# and move jobs to the correct deployment tier

nomad_jobs = {
  primary = {
    jobs = [
HEADER

  for job in "${jobs[@]}"; do
    printf '      "%s",\n' "$job" >> "$out"
  done

  cat >> "$out" <<'FOOTER'
    ]
  }

  secondary = {
    jobs = [
      # Move jobs here that depend on primary services
    ]
  }

  tertiary = {
    jobs = [
      # Move jobs here that depend on secondary services
    ]
  }
}
FOOTER

  log "Wrote $out (${#jobs[@]} jobs found)"
}

# ─── 2. Generate per-job volumes.yaml ───────────────────────────────────────

generate_volumes() {
  log "Scanning $JOBS_DIR for per-job volume declarations..."

  local jobs_written=0 jobs_skipped=0

  for job_dir in "$JOBS_DIR"/*/; do
    [[ -d "$job_dir" ]] || continue
    local job_name
    job_name="$(basename "$job_dir")"

    local volumes
    volumes=$(grep -rh --include="*.hcl" -Po 'volume\s+"\K[^"]+' "$job_dir" 2>/dev/null | sort -u || true)

    [[ -z "$volumes" ]] && continue

    local out="$job_dir/volumes.yaml"
    if [[ -f "$out" ]]; then
      log "Skipping $job_name/volumes.yaml (already exists)"
      jobs_skipped=$((jobs_skipped + 1))
      continue
    fi

    {
      for vol in $volumes; do
        local ext_id="${vol/-//}"   # first hyphen → /  (e.g. media-downloads → media/downloads)
        printf '%s:\n' "$vol"
        printf '  volume_id: %s\n' "$vol"
        printf '  external_id: %s\n' "$ext_id"
        printf '  access_mode: single-node-writer\n'
        printf '  nodes: null\n'
      done
    } > "$out"

    local vol_count
    vol_count=$(printf '%s\n' $volumes | wc -l)
    log "Wrote $job_name/volumes.yaml ($vol_count volume(s))"
    jobs_written=$((jobs_written + 1))
  done

  log "Done: $jobs_written written, $jobs_skipped skipped (already exist)"
}

# ─── 3. Generate services.auto.tfvars ─────────────────────────────────────────────

generate_env() {
  local out="$SERVICES_TFVARS/services.auto.tfvars.template"
  log "Scanning templates and terraform files for variables..."

  # 1. Extract ${var} from template files (skip Nomad runtime $${} vars)
  #    Scans: job HCL files, per-job consul_kv config files, per-job .nv.yaml vars
  local template_vars
  template_vars=$(
    grep -rhoP --include="*.hcl" '(?<!\$)\$\{\K\w+(?=\})' "$JOBS_DIR" 2>/dev/null || true
    grep -rhoP '(?<!\$)\$\{\K\w+(?=\})' "$JOBS_DIR"/*/consul_kv/* 2>/dev/null || true
    grep -rhoP '(?<!\$)\$\{\K\w+(?=\})' "$JOBS_DIR"/*/*.nv.yaml 2>/dev/null || true
  )

  # 2. Extract var.env.xxx and local.vars.xxx from .tf files
  local tf_vars
  tf_vars=$(grep -rhoP '(?:var\.env|local\.vars)\.\K\w+' \
    "$SERVICES_DIR"/*.tf 2>/dev/null \
    | sort -u)

  # 3. Combine, deduplicate, and exclude job-specific vars (version is per-job)
  local all_vars
  all_vars=$(printf '%s\n' $template_vars $tf_vars | grep -v '^version$' | sort -u)

  # 4. Find longest variable name for alignment
  local max_len=0
  for var in $all_vars; do
    (( ${#var} > max_len )) && max_len=${#var}
  done

  # 5. Write env map
  cat > "$out" <<'HEADER'
# env map - template variables used across nomad jobs, consul kv, and nomad vars
# Generated by scripts/generate-vars.sh
# Copy to /terraform/services/services.auto.tfvars and populate with real data

env = {
HEADER

  for var in $all_vars; do
    printf '  %-*s = "CHANGEME"\n' "$max_len" "$var" >> "$out"
  done

  echo "}" >> "$out"
  log "Wrote $out ($(echo $all_vars | wc -w) variables found)"
}

# ─── 4. Generate cluster.auto.tfvars ────────────────────────────────────────

generate_cluster() {
  local out="$CLUSTER_TFVARS/cluster.auto.tfvars.template"
  log "Generating cluster variable template..."

  cat > "$out" <<'EOF'
env = {
  datacenter      = "dc1" 
  cidr            = "192.168.X.0/24"
  ciuser          = "CHANGEME"
  cipassword      = "CHANGEME"
  sshkeys         = "ssh-rsa AAAA... user@host"
  tld             = "example.com"
  nameserv        = "192.168.X.X"
  pve_nodes       = ["pve01", "pve02", "pve03"]

  provider = {
    url      = "https://192.168.X.X:8006"
    user     = "root@pam"
    password = "CHANGEME"
  }

  worker = {

    clone     = "worker-tpl"
    clone_id  = 9002
    disk_size = 30
    cores     = 12
    memory    = 65536
    offset    = 81
    count     = 3
  }

  manager = {
    clone     = "manager-tpl"
    clone_id  = 9001
    disk_size = 8
    cores     = 4
    memory    = 8192
    offset    = 71
    count     = 3
  }

  vm = {
    storage             = "rbd"
    cloud_init_storage  = "cephfs"
    full_clone          = true
    cpu_type            = "host"
    agent_enabled       = true
    bridge              = "vmbr1"
    network_model       = "virtio"
    disk_interface      = "scsi0"
    disk_iothread       = true
    disk_discard        = "on"
    disk_ssd            = true
    cloudinit_interface = "ide0"
    vlan_id             = ""
  }
}
EOF

  log "Wrote $out"
}

generate_packer() {
  local out="$PACKER_PKRVARS/packer.pkrvars.template"
  log "Generating packer variable template..."

  cat > "$out" <<'EOF'
# This map contains vars that are used in packer templates
# Generated by scripts/generate-vars.sh
# Copy to /packer/packer.pkrvars and populate with real data

env = {
  proxmox_url="http://192.168.x.x:8006/api2/json"
  proxmox_user="user"
  proxmox_password="password"
  proxmox_node="node"
  ssh_username="user"
  ssh_password="password"

  os              = "os"
  cpu_type        = "cpu"
  sockets         = 1
  cores           = 2
  memory          = 2048
  machine         = "pc"
  scsi_controller = "virtio-scsi-single"
  qemu_agent      = true
  
  cloud_init              = true
  cloud_init_storage_pool = "cloud_init_storage"

  vga = {
    type = "std"
  }

  network_adapters = {
    model    = "virtio"    
    bridge   = "vmbr1"
  }

  disks = {
    disk_size    = "6G"
    storage_pool = "storage_pool"
  }

  boot = {
    type     = "scsi"
    iso      = "local:iso/debian-13.3.0-amd64-netinst.iso"
    unmount  = true
  }

}
EOF

  log "Wrote $out"
}

# ─── Main ────────────────────────────────────────────────────────────────────

echo "Generating tfvars templates from project..."
echo ""

generate_nomad_jobs
generate_volumes
generate_env
generate_cluster
generate_packer

echo ""
echo "Done. Templates written to:"
echo "  $SERVICES_TFVARS/"
echo "  $CLUSTER_TFVARS/"
echo "  $PACKER_PKRVARS/"
echo ""
echo "Review the generated files, fill in placeholder values, then copy"
echo "them to their parent directories as .auto.tfvars files."
